set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'nordtheme/tmux'
set -g @plugin 'omerxx/tmux-floax'

# Statusbar
set-option -g status-position top

# Fast config reload
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Leader key
set -g prefix C-x

# Neovim background color
set-option -a terminal-features 'alacritty:RGB'
set-option -a terminal-features 'kitty:RGB'
set-option -a terminal-features 'ghostty:RGB'

# Mouse support
set -g mouse on

# Start windows and panes at 1 and not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Sessions
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'
