OUTPUTTYPE="flac"
OUTPUTDIR="$HOME/Music"
OUTPUTFORMAT='${ARTISTFILE}/${ALBUMFILE}/${TRACKNUM}.${TRACKFILE}'
MAXPROCS=2

mungefilename ()
{
  echo "$@" | sed s,:,-,g | tr \(\)\/\<\>\|\*\? _ | tr -d \\\\\"\'
}
